### PR TITLE
Update serial conversion to use big endian only

### PR DESCRIPTION
**Pull request by damienbod**
fixes https://github.com/damienbod/AspNetCoreCertificates/issues/39

### CODE REVIEW

**Comment by damienbod** [comment]
fixes https://github.com/damienbod/AspNetCoreCertificates/issues/39

**Comment by damienbod** [comment]
@jlewis666  Maybe you could review this fix? 

I want to test this before merging and releasing. Hopefully soon :)

Greetings and thanks for reporting.

**Comment by senchden** [comment]
Hello. I'm the the reporter, but I have tried out the PR, and while the code does not crash anymore, the value does not seem to be correct.
I get HEX-string of serial number along the lines of `42000000000000004200000000000000E800000000000000610000000000000000000000000000000000000000000000000000000000000000`, which is equal to `4.797135580351005e+136`, i.e. several orders of magnitude away from the actual value.
I would probably fix it something like this:
```
var timestamp = Convert.ToUInt64((DateTime.UtcNow - DateTime.UnixEpoch).TotalSeconds);
var serialByteSpan = new Span<byte>(new byte[sizeof(ulong)]);
BinaryPrimitives.WriteUInt64BigEndian(serialByteSpan, timestamp);
var serial = serialByteSpan.ToArray();
```
The code works for me and gives the correct UNIX timestamp when decoded.
I am using `ulong` since certificate requires unsigned big int. Using `BinaryPrimitives` is recommended since it automatically accounts for endedness.
I would like someone else to verify the correctness though, since I'm not an expert on the certificates.

**Comment by damienbod** [comment]
Thanks, I'll ask for another opinion

Greetings Damien

**Comment by jlewis666** [comment]
Apologies. I am busy with family matters.

**Pull request merged**
